# Generated by Django 5.2.14 on 2026-05-18 06:24

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#9b59ff', help_text='Color de la etiqueta en la interfaz (ej. #9b59ff)', max_length=7, verbose_name='Color hex')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('saga', models.CharField(blank=True, max_length=100, verbose_name='Saga')),
                ('year', models.PositiveIntegerField(verbose_name='Año de lanzamiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('developer', models.CharField(blank=True, max_length=150, verbose_name='Desarrollador')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3, verbose_name='Calificación')),
                ('strength', models.PositiveSmallIntegerField(default=50, verbose_name='Intensidad')),
                ('speed', models.PositiveSmallIntegerField(default=50, verbose_name='Velocidad')),
                ('horror', models.PositiveSmallIntegerField(default=50, verbose_name='Terror')),
                ('replayability', models.PositiveSmallIntegerField(default=50, verbose_name='Rejugabilidad')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['title'],
            },
        ),
    ]
