# Generated by Django 5.2.14 on 2026-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='strength',
            new_name='intensity',
        ),
        migrations.RemoveField(
            model_name='game',
            name='horror',
        ),
        migrations.RemoveField(
            model_name='game',
            name='speed',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Dificultad'),
        ),
        migrations.AddField(
            model_name='game',
            name='story',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Historia'),
        ),
    ]
